{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mokelab.android.devportal",
    "module": "devportal",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mokelab.android.devportal",
          "module": "api",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.58"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "devportal-0.1.1.aar",
          "url": "devportal-0.1.1.aar",
          "size": 31375,
          "sha512": "0edce31a752a082af3ba0268825a91dc9977ce3712f81e7be70d03cea4622f7b239a46a33f42830c3b4a34bee7faca091a62918b2660a9c2ddf202a5caa654b7",
          "sha256": "c39b180edb1952d259774df712dd4dc3ba9b922c26e74ab0988b60aba1863734",
          "sha1": "b579b2b791c28a81cdc922548b391641a40c4059",
          "md5": "b5ca04bbe3869a519c3e9481cade5b80"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.mokelab.android.devportal",
          "module": "api",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.58"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "devportal-0.1.1.aar",
          "url": "devportal-0.1.1.aar",
          "size": 31375,
          "sha512": "0edce31a752a082af3ba0268825a91dc9977ce3712f81e7be70d03cea4622f7b239a46a33f42830c3b4a34bee7faca091a62918b2660a9c2ddf202a5caa654b7",
          "sha256": "c39b180edb1952d259774df712dd4dc3ba9b922c26e74ab0988b60aba1863734",
          "sha1": "b579b2b791c28a81cdc922548b391641a40c4059",
          "md5": "b5ca04bbe3869a519c3e9481cade5b80"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "devportal-0.1.1-sources.jar",
          "url": "devportal-0.1.1-sources.jar",
          "size": 6899,
          "sha512": "1a309ec76df6d9fda69b540fc1dba4605fb6034729bf983d293fe9f0757208936a1c45ac1db5525f5935bcf0182011c3728c5cd3cce3184377dac96120e7efbc",
          "sha256": "6cca49fcc37ac0369acb5eee04e49a397772ef5115855b3efc805677c4799200",
          "sha1": "c8e31389b62c2fc0f222dd4b9f157559bc16d5c4",
          "md5": "414be9e306cf2e1b79882fc332dbb764"
        }
      ]
    }
  ]
}
