{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mokelab.android.devportal",
    "module": "api",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-0.1.1.aar",
          "url": "api-0.1.1.aar",
          "size": 2967,
          "sha512": "8576b2c88a42f1dde57c5c081c0a203c22cfd9f1e9cc4c48c426596f52289ef1a93d94dff0f9732fda2ef97ec7f9cddadfa8b824d7be23793afd9ed9fb784b56",
          "sha256": "83a3f628025fafaf898725985ede86dd30a85f88de6d584e49f662a327307cfb",
          "sha1": "9deb9ed3bf50a9b52f5055ef58f38c97331e9d9f",
          "md5": "df185e3fefaec77b83d2f36b1566bc03"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.58"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-runtime",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-0.1.1.aar",
          "url": "api-0.1.1.aar",
          "size": 2967,
          "sha512": "8576b2c88a42f1dde57c5c081c0a203c22cfd9f1e9cc4c48c426596f52289ef1a93d94dff0f9732fda2ef97ec7f9cddadfa8b824d7be23793afd9ed9fb784b56",
          "sha256": "83a3f628025fafaf898725985ede86dd30a85f88de6d584e49f662a327307cfb",
          "sha1": "9deb9ed3bf50a9b52f5055ef58f38c97331e9d9f",
          "md5": "df185e3fefaec77b83d2f36b1566bc03"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-0.1.1-sources.jar",
          "url": "api-0.1.1-sources.jar",
          "size": 1622,
          "sha512": "15cac66563ab5e3b06e825b19f7f504a7323a825df1449a30cf14f3e8a023f155ca8c715b2dfc45176d392ea00dc802e05dfd769e8558247865eb0a9dab0e17a",
          "sha256": "12828dbfcc1c753b70e7801aa3ec681e5a87bc45e27f28d3d0116bbb63552478",
          "sha1": "9b0f9774a60f60159dd93c4cf45b4ebbcf03ca63",
          "md5": "ea2bd3934d54dec065c63f883cf82ddf"
        }
      ]
    }
  ]
}
