{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mokelab.android.devportal",
    "module": "logcat-core",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "logcat-core-0.1.0.aar",
          "url": "logcat-core-0.1.0.aar",
          "size": 50133,
          "sha512": "29ca8c5ddf4e3bed07fea2576f7a7c2a8979ae6be35b1127cc9a60caef6967e7cdace256e226e1f99649193d11cc8c7f34af0a694da5a1d34d79d8ec43c8270b",
          "sha256": "059e68fcac5345d11a1cea79bff2eba75380b914222e9eac49f2c7410d294495",
          "sha1": "c6c335eda32e844da0faee3836a1cb3fc079cee1",
          "md5": "99ebf8f7670e107dc22e635f7bde3fab"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mokelab.android.devportal",
          "module": "api",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.mokelab.android.devportal",
          "module": "logcat-api",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.58"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-lifecycle-viewmodel-compose",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "logcat-core-0.1.0.aar",
          "url": "logcat-core-0.1.0.aar",
          "size": 50133,
          "sha512": "29ca8c5ddf4e3bed07fea2576f7a7c2a8979ae6be35b1127cc9a60caef6967e7cdace256e226e1f99649193d11cc8c7f34af0a694da5a1d34d79d8ec43c8270b",
          "sha256": "059e68fcac5345d11a1cea79bff2eba75380b914222e9eac49f2c7410d294495",
          "sha1": "c6c335eda32e844da0faee3836a1cb3fc079cee1",
          "md5": "99ebf8f7670e107dc22e635f7bde3fab"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logcat-core-0.1.0-sources.jar",
          "url": "logcat-core-0.1.0-sources.jar",
          "size": 10751,
          "sha512": "5994e96c3858f7520938bc359201ccc279a544f39bb81af6514554fc74b6e7ce17eb8c298d30ce8c88b3927b9981bbaad3ef614a6ece4a18ec924bd801e79fe1",
          "sha256": "52ff31499530c6c78dbe845d383c166e16dc5dd0a95b8858b2cd1a569a4c93e7",
          "sha1": "85b5481d778a5ee285b10d3edfd03b3531fa555d",
          "md5": "1b60c302725b226631872fbd42dc9e31"
        }
      ]
    }
  ]
}
