{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mokelab.android.devportal",
    "module": "logcat-api",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "logcat-api-0.1.1.aar",
          "url": "logcat-api-0.1.1.aar",
          "size": 7354,
          "sha512": "fb8004a5174fceb319aff4114af288715786779f5a721cb73d0ca8b532954ccfb00a383cc5e87b5147f10eef5a4b44c44ae05f23e8b61317c02e04f5f93caa5a",
          "sha256": "1768b4b6e5c0ccc9fa71ec59c666b45a2b260e9e19a611739560bb73fa2887a9",
          "sha1": "1b6c19c94502d192b3d6d11f57d274cd8e83655f",
          "md5": "b01a1c518991d5d49c00da26a5d651ad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.58"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "logcat-api-0.1.1.aar",
          "url": "logcat-api-0.1.1.aar",
          "size": 7354,
          "sha512": "fb8004a5174fceb319aff4114af288715786779f5a721cb73d0ca8b532954ccfb00a383cc5e87b5147f10eef5a4b44c44ae05f23e8b61317c02e04f5f93caa5a",
          "sha256": "1768b4b6e5c0ccc9fa71ec59c666b45a2b260e9e19a611739560bb73fa2887a9",
          "sha1": "1b6c19c94502d192b3d6d11f57d274cd8e83655f",
          "md5": "b01a1c518991d5d49c00da26a5d651ad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logcat-api-0.1.1-sources.jar",
          "url": "logcat-api-0.1.1-sources.jar",
          "size": 2736,
          "sha512": "561b44484f3de2cac9f776b4be3a05200f9fc4087a695deb9577286acbb364ee112355ae12a3bd6f255255022cd2dfbd865d2de96f500488a11e7d549afdb6bb",
          "sha256": "5d5667d174f54de1d82dceb14437f62569ad4e2cb5db9b453f04836698c43fc5",
          "sha1": "96e1aafd97a8864a2a385521a0db962aa6a65324",
          "md5": "ef792f9a395a7e0c68f2e6c280986384"
        }
      ]
    }
  ]
}
