{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mokelab.android.devportal",
    "module": "logcat-core",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mokelab.android.devportal",
          "module": "logcat-api",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "logcat-core-0.1.1.aar",
          "url": "logcat-core-0.1.1.aar",
          "size": 50493,
          "sha512": "17609c9a40b3392c930aa8fd5f64e29b0d279e16aeac18304eb035ae2588233568600646d3c95d46528d61a1ffdfab4ec94fff5a9615a477c6f15f0fc045d656",
          "sha256": "c38183381d1f510f2ad03e07aa61b0c963d48654dbd6075b79d8f7c69cec8c69",
          "sha1": "8f98145940cc8f2946b73c506ee61dd241e7700d",
          "md5": "ef0626b828378146036205bd6a14da5a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mokelab.android.devportal",
          "module": "api",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.11.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.58"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-lifecycle-viewmodel-compose",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.mokelab.android.devportal",
          "module": "logcat-api",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "logcat-core-0.1.1.aar",
          "url": "logcat-core-0.1.1.aar",
          "size": 50493,
          "sha512": "17609c9a40b3392c930aa8fd5f64e29b0d279e16aeac18304eb035ae2588233568600646d3c95d46528d61a1ffdfab4ec94fff5a9615a477c6f15f0fc045d656",
          "sha256": "c38183381d1f510f2ad03e07aa61b0c963d48654dbd6075b79d8f7c69cec8c69",
          "sha1": "8f98145940cc8f2946b73c506ee61dd241e7700d",
          "md5": "ef0626b828378146036205bd6a14da5a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logcat-core-0.1.1-sources.jar",
          "url": "logcat-core-0.1.1-sources.jar",
          "size": 10751,
          "sha512": "5994e96c3858f7520938bc359201ccc279a544f39bb81af6514554fc74b6e7ce17eb8c298d30ce8c88b3927b9981bbaad3ef614a6ece4a18ec924bd801e79fe1",
          "sha256": "52ff31499530c6c78dbe845d383c166e16dc5dd0a95b8858b2cd1a569a4c93e7",
          "sha1": "85b5481d778a5ee285b10d3edfd03b3531fa555d",
          "md5": "1b60c302725b226631872fbd42dc9e31"
        }
      ]
    }
  ]
}
