{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mokelab.android.devportal",
    "module": "logcat-basic",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "logcat-basic-0.1.0.aar",
          "url": "logcat-basic-0.1.0.aar",
          "size": 14118,
          "sha512": "695289816ba30abe78b41f2f8e0759cea2c006b8f996a01f9fc7861bdbc94337d5beef7dfeb57ad942a9abdefe3bd74c5a68b5c8c1e7cff9e764be4d2ae23118",
          "sha256": "bc95756c27089bc0a3f1a04644075a94d8eb20f4cb24f90ff789f76dafb12a1c",
          "sha1": "ab56abc8fd0218887084ba8c2e0b7f8750ac441c",
          "md5": "0595cd6803a23be1bcea80f5c98b0474"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mokelab.android.devportal",
          "module": "logcat-api",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.58"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "logcat-basic-0.1.0.aar",
          "url": "logcat-basic-0.1.0.aar",
          "size": 14118,
          "sha512": "695289816ba30abe78b41f2f8e0759cea2c006b8f996a01f9fc7861bdbc94337d5beef7dfeb57ad942a9abdefe3bd74c5a68b5c8c1e7cff9e764be4d2ae23118",
          "sha256": "bc95756c27089bc0a3f1a04644075a94d8eb20f4cb24f90ff789f76dafb12a1c",
          "sha1": "ab56abc8fd0218887084ba8c2e0b7f8750ac441c",
          "md5": "0595cd6803a23be1bcea80f5c98b0474"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logcat-basic-0.1.0-sources.jar",
          "url": "logcat-basic-0.1.0-sources.jar",
          "size": 3669,
          "sha512": "dbce8b2671fbcc20b1c51dffbfa7f0c8904051633c2e396bb33f1a41ab03085641cc2ef872ff9c3d5c9b0410244e7eeda70fc37f3152f03c21112ea1a2533ef9",
          "sha256": "8c6a10d123f7609fee5cb4769a037eb8ded0332594404b5499a97730f63db410",
          "sha1": "3c06e56257c8aa7be67383ca1d44886406c420c2",
          "md5": "e9dae5bab53c5f5b5eaacfa7c7e4e3e9"
        }
      ]
    }
  ]
}
